docs: improve functions documentation
terramate-io/terramate pull request #1126
Opened 2023-09-04 11:58 UTC by i4ki

2023-09-06 10:07 UTC, mariux approved these changes
amazing.. ;)

2023-09-06 10:12 UTC, mariux requested changes

2023-09-06 10:12 UTC, mariux commented on docs/functions/tm_plantimestamp.md
i do not think we have this information.

2023-09-11 12:30 UTC, i4ki commented on docs/functions/tm_plantimestamp.md
we do not! I will remove it, thanks!

2023-09-13 17:46 UTC, i4ki commented on docs/functions/tm_plantimestamp.md
removed

2023-09-14 08:53 UTC, MordecaiMalignatus approved these changes

2023-09-15 16:07 UTC, i4ki commented
@mariux can you review again?

2023-09-18 09:59 UTC, i4ki commented
@soerenmartius can you have a look?

2023-09-18 16:12 UTC, merged