docs: refine terramate list command usage and examples
terramate-io/terramate pull request #1506
Opened 2024-02-29 12:29 UTC by RocketRene

## What this PR does / why we need it:
This PR refines the `terramate list` command documentation for better clarity and adherence to the Terramate Documentation Guide, specifically updating the usage section and examples.

## Does this PR introduce a user-facing change?
Yes, it updates the documentation to enhance user understanding and application of the `terramate list` command.

2024-02-29 17:08 UTC, i4ki requested changes

2024-02-29 17:08 UTC, i4ki commented on docs/cli/cmdline/list.md
> +terramate list --chdir <path>```
The ``` must go in the next line.

2024-02-29 17:08 UTC, i4ki commented on docs/.tool-versions
> +nodejs 18.19.0
is this related to this change?

2024-03-01 16:58 UTC, mariux approved these changes

2024-03-01 17:00 UTC, mariux commented on docs/cli/cmdline/list.md
> +`terramate list [options]`
what are the options?

2024-03-04 22:47 UTC, mariux submitted a review, later dismissed

2024-03-06 20:15 UTC, mariux approved these changes

2024-03-06 20:37 UTC, mariux approved these changes

2024-03-06 20:40 UTC, merged