chore: release v0.10.5
terramate-io/terramate pull request #1870
Opened 2024-09-13 18:35 UTC by i4ki

2024-09-16 08:41 UTC, snakster commented on CHANGELOG.md
>  ### Added
Nitpick, but you name it "sharing outputs" feature here, whereas in previous changelog entries, it's `outputs-sharing` experiment. Would be better to have some consistency in the naming.

2024-09-16 22:25 UTC, snakster submitted a review, later dismissed

2024-09-23 16:30 UTC, snakster submitted a review, later dismissed

2024-09-23 16:33 UTC, mariux requested changes

2024-09-23 16:33 UTC, mariux commented on CHANGELOG.md
> +- Fix "outputs-sharing" experiment to support `any` input types.
```suggestion
- Fix `outputs-sharing` experiment to use `type = any` for generated Terraform input variables in dependent stacks.
```

2024-09-23 19:28 UTC, snakster approved these changes

2024-09-23 19:57 UTC, merged