docs: updated Getting Started Guide
terramate-io/terramate pull request #959
Opened 2023-06-08 17:40 UTC by Adeniyikayodee

# Reason for This Change

Elaborate on the reasons for this change. If applicable link it
to the related issue (like `Closes #<issue>`).

Note: We are not accepting feature PR's for the time being (this will
change in the future).

## Description of Changes

Overview of what was changed.

2023-06-08 22:27 UTC, soerenmartius commented
@Adeniyikayodee please remove the changes in `docs/pnpm-lock.yaml` from this Pull Request! Thank You!

2023-06-10 17:33 UTC, i4ki commented on docs/getting-started/index.md
> +This tutorial aims to introduce you to the basic concepts of [Terramate](https://github.com/mineiros-io/terramate), and demonstrate how a filesystem-oriented code generator can improve the management
```suggestion
This tutorial aims to introduce you to the basic concepts of [Terramate](https://github.com/terramate-io/terramate), and demonstrate how a filesystem-oriented code generator can improve the management of your Terraform code efficiently.
```

2023-06-15 11:53 UTC, soerenmartius requested changes
Please resolve the conflicts

2023-06-16 10:00 UTC, soerenmartius approved these changes
lgtm!

2023-06-16 10:00 UTC, merged